export const extraConfig = [
  {
    code: 'allowRemarks',
    dataType: 'text',
    description: 'Allow Remarks',
    editable: true,
    inputType: 'checkbox',
    label: 'Allow Remarks',
    name: 'Allow Remarks',
    placeholder: 'Allow Remarks',
    renderingHints: {
      class: 'sb-g-col-lg-1',
    },
    required: false,
    visible: true,
  },
  {
    code: 'allowEvidence',
    dataType: 'text',
    description: 'Allow Evidence',
    editable: true,
    inputType: 'checkbox',
    label: 'Allow Evidence',
    name: 'Allow Evidence',
    placeholder: 'Allow Evidence',
    renderingHints: {
      class: 'sb-g-col-lg-1',
    },
    required: false,
    visible: true,
  },
  {
    code: 'canBeNotApplicable',
    dataType: 'text',
    description: 'Mark as not-mandatory',
    editable: true,
    inputType: 'checkbox',
    label: 'Mark as not-mandatory',
    name: 'Mark as not-mandatory',
    placeholder: 'Mark as not-mandatory',
    renderingHints: {
      class: 'sb-g-col-lg-1',
    },
    required: false,
    visible: true,
  },
  {
    code: 'evidence',
    dataType: 'list',
    description: 'Evidence',
    editable: true,
    inputType: 'nestedselect',
    label: 'Evidence',
    name: 'Evidence',
    placeholder: 'Select file type',
    renderingHints: {
      class: 'sb-g-col-lg-1',
    },
    default: [],
    required: false,
    visible: true,
  },
];
