
export const labelConfigDataMock = {
  "preview_collection_btn_label": "Preview",
  "preview_collection_btn_icon": "icon eye",
  "save_collection_btn_label": "Save as Draft",
  "save_collection_btn_icon": "",
  "submit_collection_btn_label": "Submit for review",
  "submit_collection_btn_icon": "",
  "reject_collection_btn_label": "Request changes",
  "reject_collection_btn_icon": "",
  "publish_collection_btn_label": "Submit for Approval",
  "publish_collection_btn_icon": "",
  "edit_question_btn_label": "Edit",
  "edit_question_btn_icon": "icon edit",
  "preview_question_btn_label": "Preview",
  "preview_question_btn_icon": "icon eye",
  "cancel_question_btn_label": "Cancel",
  "cancel_question_btn_icon": "",
  "save_question_btn_label": "Save",
  "save_question_btn_icon": "",
  "send_back_for_correction_collection_btn_label": "Send Back For Corrections",
  "send_back_for_correction_collection_btn_icon": "",
  "sourcing_approve_collection_btn_label": "Publish",
  "sourcing_approve_collection_btn_icon": "",
  "sourcing_reject_collection_btn_label": "Reject",
  "sourcing_reject_collection_btn_icon": "",
  "upload_use_btn_label": "Upload and Use",
  "cancel_btn_label": "Cancel",
  "back_btn_label": "Back",
  "search_btn_label": "Search",
  "add_btn_label": "Add",
  "upload_from_computer_btn_label": "Upload from Computer",
  "request_btn_label": "Request",
  "no_btn_label": "No",
  "yes_btn_label": "Yes",
  "close_btn_label": "Close",
  "submit_btn_label": "Submit",
  "add_sibling_btn_label": "Add Sibling",
  "add_child_btn_label": "Add Child",
  "create_new_btn_label": "Create New",
  "add_from_library_btn_label": " Add from library",
  "submit_review_btn_label": "Submit Review",
  "apply_btn_label": "Apply",
  "reset_btn_label": "Reset",
  "delete_btn_label": "Delete",
  "next_btn_label": "Next",
  "remove_btn_label": "Remove",
  "done_btn_label": "Done",
  "showPreview": false,
  "questionContribution": true,
  "title": "Subjective Question"
}
